#!/bin/bash
export PKG_PATH="$(cd "$(dirname "${BASH_SOURCE[0]-$0}")" && pwd)"

# Deprecated in new version
export hawq_config_hawq_magma_locations_master=file://${HOME}/db_data/hawq-data-directory/magma_catalog
export hawq_config_hawq_magma_locations_segment=file://${HOME}/db_data/hawq-data-directory/magma_data

export hawq_config_hawq_master_directory=${HOME}/db_data/hawq-data-directory/masterdd
export hawq_config_hawq_segment_directory=${HOME}/db_data/hawq-data-directory/segmentdd
export hawq_config_gp_vmem_idle_resource_timeout=3600000

export hawq_config_hawq_init_with_magma=false
export hawq_config_node_log_directory=${hawq_config_hawq_segment_directory}/pg_log
export hawq_config_node_data_directory=${hawq_config_hawq_magma_locations_segment}

# export hawq_config_hawq_init_with_magma=true
export hawq_config_gp_max_plan_slice=120
export hawq_config_gp_autostats_mode=ON_NO_STATS
export hawq_config_autostat_disabled=off
export hawq_config_autostat_on_no_stat=on
export hawq_config_hawq_s3_config=/usr/local/hawq/credentials
# export hawq_config_hawq_s3_config=/usr/local/hawq/fake
# export hawq_config_hawq_s3_config=none
export hawq_config_new_interconnect_type=UDP
export hawq_config_gp_interconnect_type=UDP

export hawq_config_hawq_segment_temp_directory=/tmp/hawq_segment_temp/
export hawq_config_hawq_master_temp_directory=/tmp/hawq_master_temp/
export hawq_config_optimizer=off
export hawq_config_enable_master_auto_ha=off
export hawq_config_log_components=none
export hawq_config_max_jump_hash_map_num=16

export hawq_config_autocompact_launcher_numbers=1
export hawq_config_autocompact_s3cleaner_numbers=1

export hawq_config_gp_enable_explain_allstat=on
export hawq_config_gp_resqueue_print_operator_memory_limits=on

export hawq_config_new_executor_config='explain_analyze_verbose:true'
export hawq_config_new_executor_enable_proxy_dispatcher=off
export hawq_config_new_executor_elastic_dop_per_segment=0
export hawq_config_new_executor_enable_self_tuning=on
export hawq_config_enable_result_cache=off
# export hawq_config_oushu_trace_level=summary

export hawq_config_cache_read_protocols=hdfs
export hawq_config_cache_skip_local=off

