\set hdfs_prefix hdfs://localhost:8020/hawq_default/

\set url :hdfs_prefix/nation
CREATE EXTERNAL TABLE NATION
(
    N_NATIONKEY INTEGER,
    N_NAME      TEXT,
    N_REGIONKEY INTEGER,
    N_COMMENT   TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/region
CREATE EXTERNAL TABLE REGION
(
    R_REGIONKEY INTEGER,
    R_NAME      TEXT,
    R_COMMENT   TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/part
CREATE EXTERNAL TABLE PART
(
    P_PARTKEY     INTEGER,
    P_NAME        TEXT,
    P_MFGR        TEXT,
    P_BRAND       TEXT,
    P_TYPE        TEXT,
    P_SIZE        INTEGER,
    P_CONTAINER   TEXT,
    P_RETAILPRICE FLOAT,
    P_COMMENT     TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/supplier
CREATE EXTERNAL TABLE SUPPLIER
(
    S_SUPPKEY   INTEGER,
    S_NAME      TEXT,
    S_ADDRESS   TEXT,
    S_NATIONKEY INTEGER,
    S_PHONE     TEXT,
    S_ACCTBAL   FLOAT,
    S_COMMENT   TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/partsupp
CREATE EXTERNAL TABLE PARTSUPP
(
    PS_PARTKEY    INTEGER,
    PS_SUPPKEY    INTEGER,
    PS_AVAILQTY   INTEGER,
    PS_SUPPLYCOST FLOAT,
    PS_COMMENT    TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/customer
CREATE EXTERNAL TABLE CUSTOMER
(
    C_CUSTKEY    INTEGER,
    C_NAME       TEXT,
    C_ADDRESS    TEXT,
    C_NATIONKEY  INTEGER,
    C_PHONE      TEXT,
    C_ACCTBAL    FLOAT,
    C_MKTSEGMENT TEXT,
    C_COMMENT    TEXT
) LOCATION (:'url') FORMAT 'ORC';

\set url :hdfs_prefix/orders
CREATE EXTERNAL TABLE ORDERS
(
    O_ORDERKEY      BIGINT,
    O_CUSTKEY       INTEGER,
    O_ORDERSTATUS   TEXT,
    O_TOTALPRICE    FLOAT,
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY TEXT,
    O_CLERK         TEXT,
    O_SHIPPRIORITY  INTEGER,
    O_COMMENT       TEXT
) LOCATION (:'url') FORMAT 'ORC'
;

\set url :hdfs_prefix/lineitem
CREATE EXTERNAL TABLE LINEITEM
(
    L_ORDERKEY      BIGINT,
    L_PARTKEY       INTEGER,
    L_SUPPKEY       INTEGER,
    L_LINENUMBER    INTEGER,
    L_QUANTITY      FLOAT,
    L_EXTENDEDPRICE FLOAT,
    L_DISCOUNT      FLOAT,
    L_TAX           FLOAT,
    L_RETURNFLAG    TEXT,
    L_LINESTATUS    TEXT,
    L_SHIPDATE      DATE,
    L_COMMITDATE    DATE,
    L_RECEIPTDATE   DATE,
    L_SHIPINSTRUCT  TEXT,
    L_SHIPMODE      TEXT,
    L_COMMENT       TEXT
) LOCATION (:'url') FORMAT 'ORC';
